<?php
declare(strict_types=1);

namespace OCA\SouveraShield\SetupChecks;

use OCA\SouveraShield\AppInfo\Application;
use OCP\IL10N;
use OCP\L10N\IFactory;
use OCP\SetupCheck\ISetupCheck;
use OCP\SetupCheck\SetupResult;

/**
 * Admin-overview setup check that verifies every file shipped with the
 * release (appinfo/manifest.json, generated by scripts/generate_manifest.py)
 * actually exists on this server and matches its sha256 hash.
 *
 * Born out of real-world incidents: partial deployments on shared mounts
 * left single class files missing ("Class … does not exist") or stale
 * (v0.0.0 footer). This check turns those cryptic 500s into a clear,
 * actionable message under Settings → Overview.
 */
class FileIntegrityCheck implements ISetupCheck {

    private const MAX_LISTED = 8;

    private IL10N $l10n;
    private string $appRoot;

    public function __construct(IFactory $l10nFactory, ?string $appRoot = null) {
        $this->l10n = $l10nFactory->get(Application::APP_ID);
        $this->appRoot = $appRoot ?? dirname(__DIR__, 2);
    }

    public function getCategory(): string {
        return 'system';
    }

    public function getName(): string {
        return $this->l10n->t('Souvera Shield: file integrity');
    }

    public function run(): SetupResult {
        $manifestPath = $this->appRoot . '/appinfo/manifest.json';
        if (!is_file($manifestPath)) {
            return SetupResult::warning($this->l10n->t(
                'The file manifest of the app is missing (appinfo/manifest.json) – file integrity cannot be verified. Please redeploy the complete app folder.',
            ));
        }

        $manifest = json_decode((string)file_get_contents($manifestPath), true);
        $files = is_array($manifest['files'] ?? null) ? $manifest['files'] : [];
        if ($files === []) {
            return SetupResult::warning($this->l10n->t(
                'The file manifest of the app is missing (appinfo/manifest.json) – file integrity cannot be verified. Please redeploy the complete app folder.',
            ));
        }

        $missing = [];
        $modified = [];
        foreach ($files as $relPath => $sha256) {
            $abs = $this->appRoot . '/' . $relPath;
            if (!is_file($abs)) {
                $missing[] = $relPath;
                continue;
            }
            if (hash_file('sha256', $abs) !== $sha256) {
                $modified[] = $relPath;
            }
        }

        if ($missing !== []) {
            return SetupResult::error($this->l10n->t(
                'The Souvera Shield installation is incomplete – %1$d file(s) are missing on this server: %2$s – Please redeploy the complete app folder and restart PHP-FPM afterwards.',
                [count($missing), $this->fileList($missing)],
            ));
        }

        if ($modified !== []) {
            return SetupResult::warning($this->l10n->t(
                '%1$d file(s) differ from the shipped release (possibly stale versions from an earlier update): %2$s – Please redeploy the complete app folder.',
                [count($modified), $this->fileList($modified)],
            ));
        }

        return SetupResult::success($this->l10n->t(
            'All %1$d files of Souvera Shield v%2$s are present and unmodified.',
            [count($files), (string)($manifest['version'] ?? '?')],
        ));
    }

    private function fileList(array $paths): string {
        $shown = array_slice($paths, 0, self::MAX_LISTED);
        $suffix = count($paths) > self::MAX_LISTED
            ? ' (+' . (count($paths) - self::MAX_LISTED) . ')'
            : '';
        return implode(', ', $shown) . $suffix;
    }
}
